### ISSUE TITLE
Support for docker repositories

### ISSUE THREAD

**Issue by GBrawl** [thiagofigueiro/nexus3-cli#50]
I was wondering why Docker isn't a supported format, I tried to add it and it seemed to work just fine. Can someone enlighten me?

**Comment by thiagofigueiro** [comment]
Hi, @GBrawl - it was just a matter of time/priority. When I first wrote this CLI I didn't need to manage docker repositories, so I never added support for it.

It shouldn't be too hard to add support for it on the `release/2.0.0` branch since the groovy script used to create repositories now supports arbitrary arguments. It would just be a matter of writing the model, validations and CLI interface.
