### ISSUE TITLE
nexus_client http_request calling sys.exit(1) on exception

### ISSUE THREAD

**Issue by samuelrohr** [thiagofigueiro/nexus3-cli#85]
On the file nexus_client.py line 116 it's calling sys.exit(1) in case of exception. This is preventing my system to catch and treat the error correctly. There is any reason to call a sys.exit instead of raise the exception?

**Comment by thiagofigueiro** [comment]
I can’t see the source at the moment but I don’t think so - probably an oversight of my part. 

I think nexus_client should raise the exception and cli should call sys.exit when necessary. 

If you want to submit a PR, I can review tonight, otherwise I’ll do one myself on the weekend. 

Sent on the run; please excuse my brevity.

**Comment by samuelrohr** [comment]
Hello @thiagofigueiro i submitted a PR. Thx for the reply =)
