### ISSUE TITLE
Replace docopt with Click or argparse

### ISSUE THREAD

**Issue by thiagofigueiro** [thiagofigueiro/nexus3-cli#97]
This project has outgrown docopt. It doesn't support sub-commands natively and it's all become a bit hacky.

In fact, I believe the CLI is currently broken in the master branch, preventing new releases.

**Comment by verhyppo** [comment]
as you mentioned, there are some parts that are not working properly, one that I found is the `<subcommand> --help` that always show the root help.

As a side note, `Click` is very powerful, I had the chance to use it in other projects and it's very handy, but, in my opinion, has some restrictions on the arguments which are perfectly managed here via `docopt` solution very nice (never used before, thanks for showing me how to use it), since it is auto documented.

**Comment by thiagofigueiro** [comment]
I broke the CLI on d30daee5f4d86c9b37d20df2163de26d8ca2c7e7

I'll fix this, merge the existing PRs and then cut a release before start the refactor.

My mind was set on Click but now you gave me pause again. Can you please point me to an example of these restrictions on arguments that you mentioned?

**Comment by verhyppo** [comment]
My concerns are just about the code maintainability of a large number of arguments for each command or subcommand you'll create. 

For the rest, I found it very handy.

**Comment by thiagofigueiro** [comment]
I've fixed the help for sub-commands and started a branch to try click.

So far I'm liking it a lot but I haven't gotten to the repository creation stuff yet. That's where the large number of arguments come in. I'll see what it looks like and, if it's clean, maintainable, I'll fix the tests (which should also be a fair amount of work).
